### ISSUE TITLE
no

### ISSUE THREAD

**Issue by 15736865855** [beecupbe/ae2uel_extended#1]
- Minecraft Version: 1.12.2
- AE2 Version: 0.2
- Forge Version:2860

Not Supported Thaumic Energistics Extended Life
https://www.curseforge.com/minecraft/mc-mods/thaumic-energistics-extended-life

**Comment by beecupbe** [comment]
@15736865855 fixed in v0.2.0.1 https://github.com/beecupbe/ae2uel_extended/releases/tag/0.2.0.1
