### ISSUE TITLE
Почему это не форк?

### ISSUE THREAD

**Issue by Serega007RU** [beecupbe/ae2uel_extended#11]
Почему этот репозиторий не является форком https://github.com/PrototypeTrousers/Applied-Energistics-2?
Я вижу в README.md что там написано что это форк, но по факту это не так.

**Comment by beecupbe** [comment]
за основу был взят как раз таки ае2 unofficial версии v0.55.22, который я и изменял. похоже на гитхаб когда заливал не додумался кнопку форк нажать.
