### ISSUE TITLE
Config bug B:DecorativeBlocks=false

### ISSUE THREAD

**Issue by lex1975** [beecupbe/ae2uel_extended#13]
- Minecraft Version: 1.12.2
- AE2 Version: 0.55.22-0.3.1.3
- Forge Version: forge:1.12.2-14.23.5.2860
I change file "AppliedEnergistics2.cfg" in line 226:  [AppliedEnergistics2.zip](https://github.com/beecupbe/ae2uel_extended/files/12784994/AppliedEnergistics2.zip) - I have crash
B:DecorativeBlocks=true - no crash
[crash-2023-10-02_20.28.13-client.txt](https://github.com/beecupbe/ae2uel_extended/files/12784995/crash-2023-10-02_20.28.13-client.txt)

**Comment by beecupbe** [comment]
it seems that this bug also appears on the original AE2 Unofficial Extended life.

**Comment by lex1975** [comment]
Maybe you're right. In that case, we need to do something about it:
1. Fix the bug.
2. Remove the defective parameters from the configuration file.
3. Write a warning about defective parameters on the title page of your mod.

**Comment by beecupbe** [comment]
should be fixed in v0.3.1.4 (https://github.com/beecupbe/ae2uel_extended/releases/tag/0.3.1.4)

**Comment by lex1975** [comment]
Thank you very much! The bug is fixed, I checked.
