### ISSUE TITLE
Support Neeve's AE2: Extended Life Additions

### ISSUE THREAD

**Issue by mczph** [beecupbe/ae2uel_extended#15]
![image](https://github.com/NotMyWing/NAE2/assets/103164772/b0aa1c4a-bb6f-4ad2-bb93-934e7d060426)

Modlist:
![image](https://github.com/NotMyWing/NAE2/assets/103164772/3b677b13-f41b-4bc7-86c4-e83291236a0f)

https://github.com/NotMyWing/NAE2/issues/12

**Comment by beecupbe** [comment]
the author of NAE2 needs to add support himself

**Comment by beecupbe** [comment]
https://github.com/NotMyWing/NAE2/releases/tag/1.5.1
