### ISSUE TITLE
GalactiCraft     collapse

### ISSUE THREAD

**Issue by 13193445976** [beecupbe/ae2uel_extended#16]
forge:14.23.5.2860  GalactiCraft:4.06 Collapse
[crash-2023-10-05_13.34.10-server.txt](https://github.com/beecupbe/ae2uel_extended/files/12812680/crash-2023-10-05_13.34.10-server.txt)

**Comment by 13193445976** [comment]
ae2uel_extended:0.55.23b-0.3.1.4-rv6-stable-7

**Comment by magcicada** [comment]
You should ask this issue to @embeddedt with vintagefix
