### ISSUE TITLE
appliedenergistics2-rv6-stable-7-extended_life-v0.55.24.jar

### ISSUE THREAD

**Issue by 15736865855** [beecupbe/ae2uel_extended#18]
Changelog
bunch of small fixes:
 fixed crash at bootup if decorative blocks were disabled in config

 use another method of disabling mousetweaks in AE GUIs
 disabled player inventory on the ore dict storage bus
 renamed "Slabs" to "Slab" in the lang file
 Fixed magnet card needing to be turned OFF and ON again before being usable
 Fixed CT RecipeActions not being triggered when crafted using the terminals
 Fixed item stages blocking the crafting of said items, since they are craftable on a vanilla crafting table
 Attempt to fix a interaction with bogosort leading to voiding of player items
 Fixed matter condenser singularities outputing extra singularities. by Neeve (#218)

**Comment by beecupbe** [comment]
updated
