### ISSUE TITLE
add Singularity 

### ISSUE THREAD

**Issue by 15736865855** [beecupbe/ae2uel_extended#19]
![QQ截图20231015130846](https://github.com/beecupbe/ae2uel_extended/assets/70320194/35568d83-24b1-424a-a8b6-692d6b1b6ad6)
![QQ截图20231015130836](https://github.com/beecupbe/ae2uel_extended/assets/70320194/76e29449-e73e-4d12-b343-52de233551f3)
![QQ截图20231015130824](https://github.com/beecupbe/ae2uel_extended/assets/70320194/ecf47082-9166-4ff1-862b-cf30b2a8a6cf)

**Comment by beecupbe** [comment]
not planned
