### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by Bili1Gd** [beecupbe/ae2uel_extended#21]
**Describe the bug**
When i use Crescent Hammer to remove an extended ME interface it juct crash.(Why NullPointerException?????)
Crash report below.

Win10
[错误报告-2023-10-19_18.56.50.zip](https://github.com/beecupbe/ae2uel_extended/files/13042148/-2023-10-19_18.56.50.zip)

- Minecraft Version: 1.12.2
- AE2 Version: v0.55.24-0.3.2.1
- Forge Version:14.23.5.2859

**Comment by beecupbe** [comment]
will be fixed in the next update
