### ISSUE TITLE
Pattern Interfaces don't show up in the Interface Terminal

### ISSUE THREAD

**Issue by Desempregago** [beecupbe/ae2uel_extended#22]
![2023-10-19_23 25 51](https://github.com/beecupbe/ae2uel_extended/assets/14002834/a71d93ae-e045-497f-93c1-0e44d30eaba5)
![2023-10-19_23 26 16](https://github.com/beecupbe/ae2uel_extended/assets/14002834/dbd51b08-754c-4d0b-8058-a00f6675536f)

**Comment by Desempregago** [comment]
And no, they're not hidden from the terminal.

**Comment by beecupbe** [comment]
i am already aware of this problem, and it will be fixed in the next update.
