### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by 13193445976** [beecupbe/ae2uel_extended#23]
The new ME interface is glued to the old ME interface. When the ME interface terminal is opened, it crashes.
The new ME interface and the new ME interface will not crash.

Minecraft Version: 1.12.2
AE2 Version: v0.55.24-0.3.2.1
Forge Version:14.23.5.2859

![无标题](https://github.com/beecupbe/ae2uel_extended/assets/141470182/884cb11d-21b5-440e-a216-cf103036aa8b)

**Comment by 13193445976** [comment]
When clicking Auto-synthesize items, it will also crash if too many items are synthesized at once

**Comment by beecupbe** [comment]
will be fixed in the next update

**Comment by beecupbe** [comment]
> When clicking Auto-synthesize items, it will also crash if too many items are synthesized at once

and what did you mean?

**Comment by 13193445976** [comment]
> > > 单击自动合成项目时，如果一次合成太多项目，它也会发生崩溃
> > 
> > 
> > 你什么意思？
> 
> 例如，我在AE2系统中制作“锻造台”。一次锻造一张桌子没有问题，但是如果我一次锻造很多张桌子，我会崩溃，

However, this seems to be a probabilistic trigger, which I don't know about, because that archive can't be accessed, and I can't reproduce the crash in other archives

**Comment by Bili1Gd** [comment]
but i found when new ME interface glue to new extended ME interface and when the ME interface terminal is opened, it also crashes.
