### ISSUE TITLE
Modifying config has no effect

### ISSUE THREAD

**Issue by mczph** [beecupbe/ae2uel_extended#24]
Environment:newest AE2UEL:Extended and some other addons.

I changed "I:denseCableCapacity" from 256 to 32, but in the game dense cable can transmit 256 channels(Displayed in TOP).

In addition, I think it seems that the power consumption of the wireless access point cannot be modified, even if the "wirelessCostMultiplier" is modified. In addition, when you put in 64 cards, regardless of the original data, it will reach the maximum value.Also, the displayed power consumption seems to be different from the actual one? So it may be a display problem, I'm not sure about this.
![image](https://github.com/beecupbe/ae2uel_extended/assets/103164772/f9e96627-af34-4e0f-99c5-ff992dd410b3)
![image](https://github.com/beecupbe/ae2uel_extended/assets/103164772/15b60c52-aaec-4a9a-b9a4-3cb9bab63878)

**Comment by beecupbe** [comment]
it is assumed that when installing 64 boosters, the terminals can be used anywhere. I added a note to JEI to let people know about it.
regarding the bug with the config, it was fixed in v0.3.3 (the note is also present in v0.3.3)
