### ISSUE TITLE
When ordered the craft of an advanced interface, went to view the craft and it crashed

### ISSUE THREAD

**Issue by Micola10174** [beecupbe/ae2uel_extended#26]
Describe the bug
 When ordered the craft of an advanced interface, went to view the craft and it crashed, launch the game and now it crashes all the time, please fix it

To Reproduce
We make a template for an improved ME interface, then order this interface and click the button view craft and then crash

Expected behavior
The second and subsequent output P2P nodes to work as the first one did.

Log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  HCASM (HammerLib-1.12.2-2.0.6.37.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  AE2ELCore (ae2-uel-extended-v0.55.24-0.3.3-rv6-stable-7.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/22/23 1:01 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at appeng.helpers.DualityInterface.pushPattern(DualityInterface.java:980)
	at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:714)
	at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:577)
	at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:128)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:40)
	at appeng.me.Grid.update(Grid.java:229)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:196)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1248_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_351, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5322078688 bytes (5075 MB) / 10871635968 bytes (10368 MB) up to 14025752576 bytes (13376 MB)
	JVM Flags: 7 total; -Xmx13366M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                              | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                               | 9.42                     | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | opencomputers|core                | 1.8.3                    | minecraft.jar                                       | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-7             | ae2-uel-extended-v0.55.24-0.3.3-rv6-stable-7.jar    | None                                     |
	| LCHIJA | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                        | None                                     |
	| LCHIJA | ae2stuff                          | 0.7.0-DEV                | ae2stuff-extended-v0.7.0-0.1.2.jar                  | None                                     |
	| LCHIJA | aroma1997core                     | 2.0.0.2.b167             | Aroma1997Core-1.12.2-2.0.0.2.b167.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | aroma1997sdimension               | 2.0.0.2.b89              | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                              | None                                     |
	| LCHIJA | betterbuilderswands               | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar   | None                                     |
	| LCHIJA | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
	| LCHIJA | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar               | None                                     |
	| LCHIJA | industrialupgrade                 | 3.0.3                    | IndustrialUpgrade-1.12.2-3.0.3.jar                  | None                                     |
	| LCHIJA | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.687.jar                   | None                                     |
	| LCHIJA | endertweaker                      | 1.2.3                    | EnderTweaker-1.12.2-1.2.3.jar                       | None                                     |
	| LCHIJA | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                           | None                                     |
	| LCHIJA | forestry                          | 5.8.2.422                | forestry_1.12.2-5.8.2.422.jar                       | None                                     |
	| LCHIJA | binniecore                        | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                    | None                                     |
	| LCHIJA | binniedesign                      | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                    | None                                     |
	| LCHIJA | genetics                          | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                    | None                                     |
	| LCHIJA | botany                            | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                    | None                                     |
	| LCHIJA | extrabees                         | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                    | None                                     |
	| LCHIJA | extratrees                        | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                    | None                                     |
	| LCHIJA | bookshelf                         | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | botania                           | r1.10-364                | Botania+r1.10-364.4.jar                             | None                                     |
	| LCHIJA | hammercore                        | 2.0.6.37                 | HammerLib-1.12.2-2.0.6.37.jar                       | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | botanicadds                       | 12.2.6                   | BotanicAdditions-1.12.2-12.2.6.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore                      | 2.4.20                   | BrandonsCore-1.12.2-2.4.20.162-universal.jar        | None                                     |
	| LCHIJA | chickenchunks                     | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar              | None                                     |
	| LCHIJA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.20.687.jar                   | None                                     |
	| LCHIJA | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.687.jar                   | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar      | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.28                   | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar  | None                                     |
	| LCHIJA | draconicadditions                 | 1.17.0                   | Draconic-Additions-1.12.2-1.17.0.45-universal.jar   | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.78            | EnderCore-1.12.2-0.5.78.jar                         | None                                     |
	| LCHIJA | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar       | None                                     |
	| LCHIJA | enderio                           | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderiobase                       | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderioconduits                   | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | opencomputers                     | 1.8.3                    | OpenComputers-MC1.12.2-1.8.3+274990f.jar            | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                            | None                                     |
	| LCHIJA | materialispreload                 | 1.2.5                    | materialis-1.12.2-1.2.5.jar                         | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                    | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | ftblib                            | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                  | None                                     |
	| LCHIJA | enderiomachines                   | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderiopowertools                 | 5.3.72                   | EnderIO-1.12.2-5.3.72.jar                           | None                                     |
	| LCHIJA | enderioendergy                    | 5.3.72                   | EnderIO-endergy-1.12.2-5.3.72.jar                   | None                                     |
	| LCHIJA | enderiozoo                        | 5.3.72                   | EnderIO-zoo-1.12.2-5.3.72.jar                       | None                                     |
	| LCHIJA | enderstorage                      | 2.4.9                    | EnderStorage-1.12.2-2.4.9.jar                       | None                                     |
	| LCHIJA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
	| LCHIJA | extrabotany                       | 60                       | ExtraBotany-r1.1-60-beta-hotfix.jar                 | None                                     |
	| LCHIJA | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                          | None                                     |
	| LCHIJA | zerocore                          | 1.12.2-0.1.2.9           | zerocore-1.12.2-0.1.2.9.jar                         | None                                     |
	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.68          | ExtremeReactors-1.12.2-0.4.5.68.jar                 | None                                     |
	| LCHIJA | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                               | None                                     |
	| LCHIJA | fluxnetworks                      | 4.1.0                    | FluxNetworks-1.12.2-4.1.1.34.jar                    | None                                     |
	| LCHIJA | gamestages                        | 2.0.123                  | GameStages-1.12.2-2.0.123.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | itemfilters                       | 1.0.4.2                  | ItemFilters-1.0.4.2.jar                             | None                                     |
	| LCHIJA | ftbquests                         | 1202.9.0.15              | FTBQuests-1202.9.0.15.jar                           | None                                     |
	| LCHIJA | gendustry                         | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                      | None                                     |
	| LCHIJA | gendustryjei                      | 1.0.2                    | gendustryjei-1.0.2.jar                              | None                                     |
	| LCHIJA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                     | None                                     |
	| LCHIJA | jeibees                           | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                        | None                                     |
	| LCHIJA | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                         | None                                     |
	| LCHIJA | jmapstages                        | @VERSION@                | jmapstages-cont-1.12.2-2.1.0.jar                    | None                                     |
	| LCHIJA | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar             | None                                     |
	| LCHIJA | libnine                           | 1.2.1                    | libnine-1.12.2-1.2.1.jar                            | None                                     |
	| LCHIJA | threng                            | 1.1.26                   | lazy-ae2-1.12.2-1.1.26.jar                          | None                                     |
	| LCHIJA | magicbees                         | 1.0                      | MagicBees-1.12.2-3.1.10.jar                         | None                                     |
	| LCHIJA | materialis                        | 1.2.5                    | materialis-1.12.2-1.2.5.jar                         | None                                     |
	| LCHIJA | moartinkers                       | 0.6.0                    | moartinkers-0.6.0.jar                               | None                                     |
	| LCHIJA | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                       | None                                     |
	| LCHIJA | harvestcraft                      | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                     | None                                     |
	| LCHIJA | powerutils                        | 1.5.3                    | Power+Utilities.jar                                 | None                                     |
	| LCHIJA | quantum_generators                | 1.3.1                    | Quantum_Generators.jar                              | None                                     |
	| LCHIJA | simplyquarries                    | 1.6.2                    | Simply+Quarries.jar                                 | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar        | None                                     |
	| LCHIJA | simplyjetpacks                    | 1.12.2-2.2.20.0          | SimplyJetpacks2-1.12.2-2.2.20.0.jar                 | None                                     |
	| LCHIJA | taiga                             | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                              | None                                     |
	| LCHIJA | thermalcultivation                | 0.3.6                    | ThermalCultivation-1.12.2-0.3.6.1-universal.jar     | None                                     |
	| LCHIJA | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar      | None                                     |
	| LCHIJA | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                  | None                                     |
	| LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                 | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin        | 1.4                      | tlskincape_1.12.2-1.4.jar                           | None                                     |
	| LCHIJA | wanionlib                         | 1.12.2-2.9               | WanionLib-1.12.2-2.9.jar                            | None                                     |
	| LCHIJA | unidict                           | 1.12.2-3.0.10            | UniDict-1.12.2-3.0.10.jar                           | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
HCASM (HammerLib-1.12.2-2.0.6.37.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.b167.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  li.cil.oc.common.asm.ClassTransformer
AE2ELCore (ae2-uel-extended-v0.55.24-0.3.3-rv6-stable-7.jar)
  appeng.core.transformer.AE2ELTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  wanion.unidict.core.UniDictCoreModTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2847
	HammerCore Debug Information: 
		Dependent Mods:
			-Botanic Additions (botanicadds) @ 12.2.6

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/micol/AppData/Roaming/.minecraft/libraries/org/tlauncher/authlib/1.6.251/authlib-1.6.251.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from ae2-uel-extended-v0.55.24-0.3.3-rv6-stable-7.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.68.jar
		* BotaniaAPI (93) from Botania+r1.10-364.4.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.6.1-universal.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.3.72.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.422.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.422.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* jeresources|API (0.9.2.60) from JustEnoughResources-1.12.2-0.9.2.60.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.7.1.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.16.1.301.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.8.3+274990f.jar
		* redstonefluxapi (2.1.1) from RedstoneFlux-1.12-2.1.1.1-universal.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
	AE2 Integration: IC2:OFF, GTCE:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['micola10174'/295, l='Выжывание 1', x=265.07, y=63.00, z=257.42]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.2.05.zip
	OpenGlVersion: 4.6.0 NVIDIA 535.98
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by beecupbe** [comment]
will be fixed in the next update
