### ISSUE TITLE
Bad compatibility with Thaumic Energistics

### ISSUE THREAD

**Issue by Bili1Gd** [beecupbe/ae2uel_extended#29]
crash when place ME Essentia interface
when use original AE2 or AE2UEL it wont happen
it happen only with AE2UELEX
[错误报告-2023-11-4_11.11.26.zip](https://github.com/beecupbe/ae2uel_extended/files/13255718/-2023-11-4_11.11.26.zip)

**Comment by Bili1Gd** [comment]
*me Essentia terminal

**Comment by beecupbe** [comment]
the problem occurs due to NAE2, try updating it to the latest version 1.5.3
(https://github.com/NotMyWing/NAE2/releases/tag/1.5.3)

**Comment by Bili1Gd** [comment]
oops it's truly occurs due to NAE2
