### ISSUE TITLE
Conflict with Custom NPCs (ver. CustomNPCs_1.12.2-03Feb22snapshot)

### ISSUE THREAD

**Issue by andre40000k** [beecupbe/ae2uel_extended#3]
Conflict with Custom NPCs (ver.CustomNPCs_1.12.2-03Feb22snapshot)

Describe the bug
EN
Avtocraft stops in the process
Resources are not defined in the system
Resources cannot be removed from the system
The system does not see resources
RU
Автокрафт останавливается в процессе
Ресурсы не определены в системе
Ресурсы невозможно удалить из системы
Система не видит ресурсы

To Reproduce
EN
The system should have a lot of resources and long crafting chains. When ordering an item, a warning appears about the lack of resources (for example, there is not enough redstone, and there are about 10k in the system, while from this moment the redstone itself cannot be taken from the system). For craft chains I using IU  (Industrial Upgrade)
RU
В системе должно быть много ресурсов и длинные цепочки крафта. При заказе предмета появляется предупреждение о нехватке ресурсов (например, редстоуна недостаточно, а в системе их около 10к, при этом сам редстоун с этого момента невозможно забрать из системы). Для цепочек крафта я использую IU (Industrial Upgrade)

Minecraft Version: 1.12.2
AE2 Version: ae2-uel-extended-v0.55.22-0.2.1.1-rv6-stable-7
Forge Version: 1.12.2-forge-14.23.5.2855
Custom NPCs Version: CustomNPCs_1.12.2-03Feb22snapshot

**Comment by beecupbe** [comment]
интересно, а откуда вы взяли CustomNPC 03Feb22snapshot, лично я смог найти только 1.12.2-(05Jul20)

**Comment by andre40000k** [comment]
1. Текущая версия CustomNPC взята с официального Дискорд канала разработчика. Почему-то он не выкладывает на Curseforge.
2. Как вам удобнее переслать видео, могу через Дискорд (скину ссылку на сервер нейтральный или можем на Дискорд сервере IU связаться), могу через другую более удобную площадку(файлообменник)

**Comment by beecupbe** [comment]
в дискорд отправьте мне заявку в друзья и в лс видос (если что тег beecube)

**Comment by beecupbe** [comment]
решили все в дискорде
