### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Fisher148** [beecupbe/ae2uel_extended#37]
**Describe the bug**

Я спросил ChatGPT, потому что я в этом не разбираюсь:
java.lang.NoClassDefFoundError для net.minecraftforge.client.model.ICustomModelLoader: Эта ошибка указывает на отсутствие класса, который не может быть найден при запуске Minecraft с модами.

ClassNotFoundException и NoClassDefFoundError для других классов из пакета net.minecraftforge и net.minecraft.client: Аналогичные проблемы с отсутствующими классами.

Ошибка с SideTransformer: В краш-репорте указана проблема с SideTransformer, что может указывать на проблему с конфигурацией сервера или совместимостью модов.

**Crash Report: https://mclo.gs/X4HExqe**

- Minecraft Version: 1.12.2
- AE2 Version: ae2-uel-extended-v0.55.30-0.4-rv6-stable-7 (https://www.curseforge.com/minecraft/mc-mods/ae2-uel-extended/files/5002156)
- Forge Version: 1.12.2 (14.23.5.2859)

**Comment by beecupbe** [comment]
пофиксил этот и ещё один краш в новых версиях AE2 UEL Extended и AE2 Stuff Unofficial Extended (https://github.com/beecupbe/ae2uel_extended/releases/tag/0.4.0.2  и https://github.com/beecupbe/ae2stuff_extended/releases/tag/v0.2.1)
