### ISSUE TITLE
The game crashed;AE2 Unofficial Extended and AE2 Fluid Crafting Reworkcollapse;

### ISSUE THREAD

**Issue by SenjumaruShutara** [beecupbe/ae2uel_extended#44]
AE2 Unofficial Extended V0.55.30-0.4.0.2; AE2 Fluid Crafting V2.5.6

The game crashed while ordering "Vacuum Impulse Itemduct",
[crash-2024-02-01_10.25.47-client.txt](https://github.com/beecupbe/ae2uel_extended/files/14119525/crash-2024-02-01_10.25.47-client.txt)

**Comment by SenjumaruShutara** [comment]
You can enter the game normally, but when you order a recipe that requires fluid participation, the game will not respond for a long time, and you can only force out of the game

**Comment by LiamThomp** [comment]
This is a fork of Applied Energistics 2 Unofficial Extended Life already, as such, it already has reworked fluid crafting, see the original of this fork for more information.

Link to the AE2UEL fork GitHub: https://github.com/AE2-UEL/Applied-Energistics-2?tab=readme-ov-file#applied-energistics-2-unofficial-extended-life

**Comment by SenjumaruShutara** [comment]
> This is a fork of Applied Energistics 2 Unofficial Extended Life already, as such, it already has reworked fluid crafting, see the original of this fork for more information.
> 
> Link to the AE2UEL fork GitHub: https://github.com/AE2-UEL/Applied-Energistics-2?tab=readme-ov-file#applied-energistics-2-unofficial-extended-life

Maybe what I'm saying is wrong, I mean this happens when "ae2uel_extended" is used

**Comment by SenjumaruShutara** [comment]
Too bad AE2 Fluid Crafting Rework explicitly says it won't support ae2uel_extended.
https://github.com/AE2-UEL/AE2FluidCraft-Rework/issues/141
