### ISSUE TITLE
Everytime I open a pattern terminal my game lags and crashes

### ISSUE THREAD

**Issue by BloxMaster3** [beecupbe/ae2uel_extended#46]
**Describe the bug**
everytime i open a pattern terminal my game lags and crashes and i cant find a solution

**To Reproduce**
I think it only happens in my world so I don't know how you would reproduce it

**Expected behavior**
i can open my pattern terminal and use it without crashing
**Additional context**
doesn't give me crash report 
**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2860
I have a discord if you would like to contact me @BloxMaster3

**Comment by SenjumaruShutara** [comment]
Do you use the "AE2 Fluid Crafting Rework"mod, if you use this mod, please delete it, it does not support AE2 uel Extended.

**Comment by BloxMaster3** [comment]
no, i don't see it in my mod folder and i dont remember downloading it

**Comment by Inbalurgator** [comment]
> Do you use the "AE2 Fluid Crafting Rework"mod, if you use this mod, please delete it, it does not support AE2 uel Extended.

it can support AE2 uel Extended however it has some bug
and the crash didn't happen to my game even though AE2FCRework installed

**Comment by BloxMaster3** [comment]
I fixed it, though I don't know what caused it
I think adding the performance and bug fixing mods in this list helped tremendously
https://github.com/Radk6/ActuallyUsefulMods
(edit: for got to actually include the list. Whoops)

**Comment by SenjumaruShutara** [comment]
> > 你使用“AE2 Fluid Crafting Rework”mod吗，如果你使用这个mod，请删除它，它不支持AE2 uel Extended。
> 
> 它可以支持 AE2 uel Extended，但是它有一些错误，即使安装了 AE2FCRework，我的游戏也没有发生崩溃

But when I use 'AE2 Fluid Crafting Rework', the game has a lag crash when I place a fluid order
