### ISSUE TITLE
Crash on Wireless Crafting Terminal

### ISSUE THREAD

**Issue by fentianx** [beecupbe/ae2uel_extended#5]
[minecraft-exported-crash-info-2023-09-22T11-40-03.zip](https://github.com/beecupbe/ae2uel_extended/files/12696727/minecraft-exported-crash-info-2023-09-22T11-40-03.zip)
[crash-2023-09-22_11.53.26-client.txt](https://github.com/beecupbe/ae2uel_extended/files/12696746/crash-2023-09-22_11.53.26-client.txt)

**Comment by beecupbe** [comment]
@fentianx fixed in v0.2.2.2 https://github.com/beecupbe/ae2uel_extended/releases/tag/0.2.2.2
