### ISSUE TITLE
more function

### ISSUE THREAD

**Issue by 15736865855** [beecupbe/ae2uel_extended#6]
1.When using memory card on p2p interfaces, copy settings, storage, and upgrades over to the new P2P instance.
2.Added ability to encode (infinite inputs -> infinite outputs) recipes.
3.Add OreDict Filter Card.
4.Add ultra dense cable (256 Channels).
5.Add mirrored interface as "P2P Tunnel - ME Interface ".
6.Add super Acceleration Card (faster).

**Comment by beecupbe** [comment]
1. p2p interfaces??
2. i'll try to implement it
3. where will this "card" be used?
4. original dense cables already transmit 256 channels
5. what will this interface do?
6. will be added in v0.2.3

**Comment by 15736865855** [comment]
Suggest taking a look at GTNH's AE
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial

**Comment by yuanju-qwq** [comment]
P2P Tunnel - ME Interface can let the player achieve physical parallelism, such as multiple identical machines, I only need to put a sample, can achieve multiple machine feeding, physical parallelism

**Comment by yuanju-qwq** [comment]
P2P Tunnel - ME Interface can let the player achieve physical parallelism, such as multiple identical machines, I only need to put a sample, can achieve multiple machine feeding, physical parallelism

**Comment by beecupbe** [comment]
1. not planned
2. not planned 
3. use oredict storage bus
4. use dense cables
5. not planned
6. no need
