### ISSUE TITLE
Model is missing

### ISSUE THREAD

**Issue by tier940** [beecupbe/ae2uel_extended#7]
AE2 UEL: Extended version - v0.55.22-0.2.2.2-rv6-stable-7

I noticed this while describing a [CoreMod](https://github.com/GTModpackTeam/GTExpert-Core/pull/149) that uses AE2UELE. There is no problem without it, but I think it is fine to fix it at the time of other modifications or updates.
![image](https://github.com/beecupbe/ae2uel_extended/assets/11691836/bb5e9a02-1241-4d61-b2f6-f80773828e18)

**Comment by beecupbe** [comment]
oh, will be fixed in v0.2.3

**Comment by beecupbe** [comment]
fixed in 0.3 =) (https://github.com/beecupbe/ae2uel_extended/releases/tag/0.3)
and sorry for the long wait
