### ISSUE TITLE
[Request] 5x5, 7x7, 9x9 (Auto)crafting

### ISSUE THREAD

**Issue by fentianx** [beecupbe/ae2uel_extended#9]
Describe the feature

Adding larger crafting terminals, larger patterns and molecular assemblers.
For example, adding "Extreme Crafting Terminal" and "Extreme Pattern" which has 9x9 capacity, and "Extreme Molecular Assembler" which has 9x9 grid.

Reasons why it should be considered

A lot of people (including me) loves playing expert mode packs. And later in the game you get some pretty nasty craftings. Managing big craft like that all inside the me system would be awesome! Plus, I (an induvidual which is obsessed with automation) would really be glad if I could automate NxN crafts. Basically this would be a gamechanger.

**Comment by beecupbe** [comment]
the answer was given above
